leituras = {
    "CGH APARECIDA": {
        "ip": "100.110.212.125",
        "port": 8010,
        "table": "cgh_aparecida",
        "CLPS": {
            "UG-01": {
                'conexao': {
                    'ip': '192.168.10.2',
                    'port': 502
                }, 
                'regras': {
                    'potência máxima': 3350,
                    'nivel de água vertimento': 405.28,
                    'nivel de água vazão sanitária': 402.10,
                    'velocidade máxima': 450,
                    'diferencial de grade UG-01': 0.80,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407,"INT",{"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321,"INT",{"offset": -1, "converter": "word_order"}],
                    "Nivel montante": [13519,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nivel jusante UG-01": [13521,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Função de religamento automático": [12321,"BOOLEAN",{"offset": -1, "converter": "word_order"}],
                },
                "temperaturas": {
                    "Enrolamento Fase A value": [13469,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase A alarmes": [13989,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase A trip": [13925,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase B value": [13471,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase B alarmes": [13991,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase B trip": [13927,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase C value": [13473,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase C alarmes": [13993,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Enrolamento Fase C trip": [13929,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 1 value": [13455,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 1 alarmes": [13975,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 1 trip": [13911,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 2 value": [13457,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 2 alarmes": [13977,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 2 trip": [13913,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 3 value": [13459,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 3 alarmes": [13979,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Tiristor 3 trip": [13915,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 1 value": [13461,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 1 alarmes": [13983,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 1 trip": [13919,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 2 value": [13491,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 2 alarmes": [13411,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Resistor Crowbar 2 trip": [13497,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Transf. Exitação value": [13463,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Transf. Exitação alarmes": [13983,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Transf. Exitação trip": [13919,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.R.V. value": [13465,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.R.V. alarmes": [13985,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.R.V. trip": [13921,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.L.M. value": [13467,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.L.M. alarmes": [13987,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Óleo U.H.L.M. trip": [13923,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 1 value": [13475,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 1 alarmes": [13995,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 1 trip": [13931,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 2 value": [13477,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 2 alarmes": [13997,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 2 trip": [13933,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 3 value": [13479,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 3 alarmes": [13999,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Nucleo Estator 3 trip": [13935,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Manc. Casq. Rad. Guia value": [13481,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Manc. Casq. Rad. Guia alarmes": [14001,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Manc. Casq. Rad. Guia trip": [13937,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Casq value": [13483,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Casq alarmes": [14003,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Casq trip": [13939,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Esc. value": [13485,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Esc. alarmes": [14005,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Esc. trip": [13941,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Contra Esc. value": [13487,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Contra Esc. alarmes": [14007,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Comb. Contra Esc. trip": [13943,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Guia Casq. Turb. value": [13489,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Guia Casq. Turb. alarmes": [14009,"REAL",{"offset": -1, "converter": "word_order"}],
                    "Mancal Guia Casq. Turb. trip": [13945,"REAL",{"offset": -1, "converter": "word_order"}],
                },
            },
        }
    },
    "CGH FAE": {
        "ip": "100.106.33.66",
        "port": 8010,
        "table": "cgh_fae",
        "CLPS": {
            "PSA": {
                'conexao': {
                    'ip': '192.168.10.4',
                    'port': 502
                }, 
                'regras': {
                    'nivel de água vertimento': 701.15,
                    'nivel de água vazão sanitária': 701.06,
                    'diferencial de grade UG-01': 0.30, # (nivel montante - nivel jusante UG-01)
                    'diferencial de grade UG-02': 0.30 # (nivel montante - nivel jusante UG-02)
                },
                'leituras': {
                    "Nivel montante": [13353, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel jusante UG-01": [13379, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel jusante UG-02": [13381, "REAL", {"offset": -1, "converter": "word_order"}],
                },
            },
            "UG-01": {
                'conexao': {
                    'ip': '192.168.10.2',
                    'port': 502
                }, 
                'regras': {
                    'potência máxima': 1350,
                    'velocidade máxima': 415,
                },
                'leituras': {
                    "Potência Ativa": [13407,"INT",{"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321,"INT",{"offset": -1, "converter": "word_order"}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "vibrações": {
                    'Vib. Mancal Guia X value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Guia X alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Guia X trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Guia Y value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Guia Y alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Guia Y trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. X value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. X alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. X trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Y value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Y alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Y trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Z value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Z alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vib. Mancal Comb. Z trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
            "UG-02": {
                'conexao': {
                    'ip': '192.168.10.3',
                    'port': 502
                },
                'regras': {
                    'potência máxima': 650,
                    'velocidade máxima': 800,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Combinado trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                    'ENGEXC value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'ENGEXC alarmes': [13997, "REAL", {"offset": -1, "converter": "word_order"}],
                    'ENGEXC trip': [13933, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CSS-U1 value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CSS-U1 alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CSS-U1 trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
        },
    },
    "PCH PEDRAS": {
        "ip": "100.93.237.40",
        "port": 8010,
        "table": "pch_pedras",
        "CLPS": {
            "PSA": {
                'conexao': {
                    'ip': '192.168.10.5',
                    'port': 502
                },
                'regras': {
                    'nivel de água vertimento': 1097.50,
                    'nivel de água vazão sanitária': 1096.72,
                    'diferencial de grade UG-01': 0.70, # (nivel montante - nivel jusante UG-01)
                    'diferencial de grade UG-02': 0.70, # (nivel montante - nivel jusante UG-02)
                },
                'leituras': {
                    "Nivel montante": [13353, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel jusante UG-01": [13355, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel jusante UG-02": [13357, "REAL", {"offset": -1, "converter": "word_order"}],
                },
            },
            "UG-01": {
                'conexao': {
                    'ip': '192.168.10.2',
                    'port': 502
                }, 
                'regras': {
                    'potência máxima': 1200,
                    'velocidade máxima': 625,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13481, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [14001, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13937, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13479, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13999, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13935, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
            "UG-02": {
                'conexao': {'ip': '192.168.10.3', 'port': 502}, 
                'regras': {
                    'potência máxima': 1200,
                    'velocidade máxima': 625,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.A. Guia trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Guia trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'G Mancal L.N.A. Escora trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 01 trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Bucha Radial 02 trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 01 trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 02 trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'T Gaxeteiro 03 trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13481, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [14001, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13937, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13479, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13999, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13935, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
        }
    },
    "CGH PICADAS ALTAS": {
        "ip": "100.79.241.13",
        "port": 8010,
        "table": "cgh_picadas_altas",
        "CLPS": {
            "UG-01": {
                'conexao': {'ip': '192.168.10.2', 'port': 502}, 
                'regras': {
                    'nivel de água vertimento': 416.50,
                    'nivel de água vazão sanitária': 416.20,
                    'diferencial de grade UG-01': 0.70, # (nivel montante - nivel jusante UG-01)
                    'pressão montante mímima': 1.00,
                    'potência máxima': 340,
                    'velocidade máxima': 1200,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Nivel Montante": [13519, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel Jusante UG-01": [13521, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Pressão Montante": [13313, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
            "UG-02": {
                'conexao': {'ip': '192.168.10.3', 'port': 502}, 
                'regras': {
                    'nivel de água vertimento': 416.50,
                    'nivel de água vazão sanitária': 416.20,
                    'diferencial de grade UG-02': 0.70, # (nivel montante - nivel jusante UG-02)
                    'pressão montante mímima': 1.00,
                    'potência máxima': 700,
                    'velocidade máxima': 1200,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Nivel Montante": [13519, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel Jusante UG-02": [13521, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Pressão Montante": [13313, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-U2 trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Rad. L.A. trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Comb. Esc. L.A. trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Manc. Cont. Esc. L.A. trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Guia L.N.A. trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
        }
    },
    "CGH HOPPEN": {
        "ip": "100.73.37.105",
        "port": 8010,
        "table": "cgh_hoppen",
        "CLPS": {
            "UG-01": {
                'conexao': {'ip': '192.168.10.2', 'port': 502}, 
                'regras': {
                    'nivel de água vertimento': 869.90,
                    'nivel de água vazão sanitária': 868.80,
                    'diferencial de grade UG-01': 0.30, # (nivel montante - nivel jusante UG-01)
                    'pressão montante mímima': 1.00,
                    'potência máxima': 1300,
                    'velocidade máxima': 500,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Nivel Montante": [13519, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel Jusante UG-01": [13521, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Pressão Montante": [13367, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. value': [13477, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. alarmes': [13997, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. trip': [13933, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13479, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13999, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13935, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13481, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [14001, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13937, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 value': [13483, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 alarmes': [14003, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 trip': [13939, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
            "UG-02": {
                'conexao': {'ip': '192.168.10.3', 'port': 502}, 
                'regras': {
                    'nivel de água vertimento': 869.90,
                    'nivel de água vazão sanitária': 868.80,
                    'diferencial de grade UG-02': 0.30, # (nivel montante - nivel jusante UG-02)
                    'pressão montante mímima': 1.00,
                    'potência máxima': 1300,
                    'velocidade máxima': 500,
                    'religamento automático': True,
                },
                'leituras': {
                    "Potência Ativa": [13407, "INT", {"offset": -1, "converter": "word_order"}],
                    "Nivel Montante": [13519, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Nivel Jusante UG-02": [13521, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Pressão Montante": [13367, "REAL", {"offset": -1, "converter": "word_order"}],
                    "Turbina Velocidade": [13321, "INT", {"offset": -1, "converter": "word_order"}],
                    "Religamento Automático": [12323, "BOOLEAN", {"offset": -1}],
                },
                "temperaturas": {
                    'Enrolamento Fase A value': [13455, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A alarmes': [13975, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase A trip': [13911, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B value': [13457, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B alarmes': [13977, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase B trip': [13913, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C value': [13459, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C alarmes': [13979, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Enrolamento Fase C trip': [13915, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator value': [13461, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator alarmes': [13981, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Nucleo do estator trip': [13917, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA value': [13463, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA alarmes': [13983, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LNA trip': [13919, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA value': [13465, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA alarmes': [13985, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Vedação do eixo LA trip': [13921, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado value': [13467, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado alarmes': [13987, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Escora Combinado trip': [13923, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado value': [13469, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado alarmes': [13989, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Combinado trip': [13925, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. value': [13471, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. alarmes': [13991, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Cont. Esc. Manc. Comb. trip': [13927, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia value': [13473, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia alarmes': [13993, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Radial Guia trip': [13929, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. value': [13475, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. alarmes': [13995, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.A. trip': [13931, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. value': [13477, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. alarmes': [13997, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Mancal Rad. Comb. L.N.A. trip': [13933, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. value': [13479, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. alarmes': [13999, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.R.V. trip': [13935, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. value': [13481, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. alarmes': [14001, "REAL", {"offset": -1, "converter": "word_order"}],
                    'Óleo U.H.L.M. trip': [13937, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 value': [13483, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 alarmes': [14003, "REAL", {"offset": -1, "converter": "word_order"}],
                    'CS-01 trip': [13939, "REAL", {"offset": -1, "converter": "word_order"}],
                },
                "alarmes": {
                    "[01.00] - PCP-U1 - Botão de Emergência Acionado": [24289, "BOOLEAN", {"offset": -1}],
                    "[01.01] - PCP-U1 - Botão de Emergência Acionado - SuperSEP": [24290, "BOOLEAN", {"offset": -1}],
                },
                "comandos": {
                    "Reset SuperSEP": [12529, "BOOLEAN", {"offset": -1}],
                    "CalaSirene SuperSEP": [12532, "BOOLEAN", {"offset": -1}],
                }
            },
        }
    }
}