valores = {
    'CGH APARECIDA': {
        'UG-01': {
            "Tiristor 1": {"alarme": 70.0, "trip": 90.0},
            "Tiristor 2": {"alarme": 500.0, "trip": 550.0},
            "Tiristor 3": {"alarme": 70.0, "trip": 90.0},
            "Resistor Crowbar 01": {"alarme": 100.0, "trip": 120.0},
            "Transformador de Excitação": {"alarme": 75.0, "trip": 90.0},
            "Óleo U.H.R.V.": {"alarme": 50.0, "trip": 60.0},
            "Óleo U.H.L.M.": {"alarme": 50.0, "trip": 60.0},
            "Temp Enrol A": {"alarme": 90.0, "trip": 110.0},
            "Temp Enrol B": {"alarme": 90.0, "trip": 110.0},
            "Temp Enrol C": {"alarme": 90.0, "trip": 110.0},
            "Núcleo Estator 1": {"alarme": 90.0, "trip": 110.0},
            "Núcleo Estator 2": {"alarme": 90.0, "trip": 110.0},
            "Núcleo Estator 3": {"alarme": 90.0, "trip": 110.0},
            "Mancal Radial Guia": {"alarme": 65.0, "trip": 70.0},
            "Mancal Comb. Casq.": {"alarme": 68.0, "trip": 70.0},
            "Mancal Comb. Esc.": {"alarme": 60.0, "trip": 65.0},
            "Mancal Comb. Contra Esc.": {"alarme": 55.0, "trip": 65.0},
            "Mancal Guia Casq. Turb.": {"alarme": 65.0, "trip": 75.0},
            "Resistor Crowbar D02": {"alarme": 55.0, "trip": 65.0},
            },
    },
    'CGH FAE': {
        'UG-01': {
            "Enrolamento Fase A": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase B": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase C": {"alarme": 100.0, "trip": 110.0},
            "Núcleo Estator": {"alarme": 100.0, "trip": 110.0},
            "CSS-U1": {"alarme": 70.0, "trip": 80.0},
            "Mancal Guia": {"alarme": 65.0, "trip": 75.0},
            "Mancal Combinado": {"alarme": 70.0, "trip": 75.0},
            "Mancal Escora": {"alarme": 60.0, "trip": 75.0},
            "Óleo U.H.R.V.": {"alarme": 55.0, "trip": 65.0},
            "Óleo U.H.L.M.": {"alarme": 55.0, "trip": 65.0},
            "Engeexc": {"alarme": 85.0, "trip": 95.0},
            "Vib. Mancal Guia X": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Guia Y": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. X": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. Y": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. Z": {"alarme": 5.50, "trip": 7.50},
        },
        'UG-02': {
            "Enrolamento Fase A": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase B": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase C": {"alarme": 100.0, "trip": 110.0},
            "Núcleo Estator": {"alarme": 100.0, "trip": 110.0},
            "CSS-U1": {"alarme": 70.0, "trip": 80.0},
            "Mancal Guia": {"alarme": 65.0, "trip": 75.0},
            "Mancal Combinado": {"alarme": 70.0, "trip": 75.0},
            "Mancal Escora": {"alarme": 60.0, "trip": 75.0},
            "Óleo U.H.R.V.": {"alarme": 55.0, "trip": 65.0},
            "Óleo U.H.L.M.": {"alarme": 55.0, "trip": 65.0},
            "Engeexc": {"alarme": 85.0, "trip": 95.0},
            "Vib. Mancal Guia X": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Guia Y": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. X": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. Y": {"alarme": 5.50, "trip": 7.50},
            "Vib. Mancal Comb. Z": {"alarme": 5.50, "trip": 7.50},
        },
    },
    'CGH PICADAS ALTAS': {
        'UG-01': {
            "Enrolamento Fase A": {"alarme": 85.0, "trip": 95.0},
            "Enrolamento Fase B": {"alarme": 85.0, "trip": 95.0},
            "Enrolamento Fase C": {"alarme": 85.0, "trip": 95.0},
            "Núcleo Estator": {"alarme": 85.0, "trip": 95.0},
            "CS-U1": {"alarme": 55.0, "trip": 65.0},
            "Mancal Comb. Rad. L.A.": {"alarme": 55.0, "trip": 65.0},
            "Mancal Comb. Esc. L.A.": {"alarme": 62.0, "trip": 65.0},
            "Mancal Cont. Esc. L.A.": {"alarme": 55.0, "trip": 60.0},
            "Mancal Guia L.N.A.": {"alarme": 55.0, "trip": 60.0},
            "Ug01 Óleo Reservatório - U.H.L.M*": {"alarme": 55.0, "trip": 65.0},
        },
        'UG-02': {
            "Enrolamento Fase A": {"alarme": 85.0, "trip": 95.0},
            "Enrolamento Fase B": {"alarme": 85.0, "trip": 95.0},
            "Enrolamento Fase C": {"alarme": 85.0, "trip": 95.0},
            "Núcleo Estator": {"alarme": 85.0, "trip": 95.0},
            "CS-U1": {"alarme": 55.0, "trip": 60.0},
            "Mancal Comb. Rad. L.A.": {"alarme": 60.0, "trip": 70.0},
            "Mancal Comb. Esc. L.A.": {"alarme": 62.0, "trip": 65.0},
            "Mancal Cont. Esc. L.A.": {"alarme": 55.0, "trip": 60.0},
            "Mancal Guia L.N.A.": {"alarme": 55.0, "trip": 60.0},
            "Ug02 Óleo Reservatório - U.H.L.M*": {"alarme": 55.0, "trip": 60.0},
        }
    },
    'PCH PEDRAS': {
        'UG-01': {
            "Enrolamento Fase A": {"alarme": 105.0, "trip": 110.0},
            "Enrolamento Fase B": {"alarme": 105.0, "trip": 110.0},
            "Enrolamento Fase C": {"alarme": 105.0, "trip": 110.0},
            "Mancal L.A. Guia": {"alarme": 65.0, "trip": 72.0},
            "Mancal L.N.A. Guia": {"alarme": 80.0, "trip": 85.0},
            "Mancal L.N.A. Escora": {"alarme": 92.0, "trip": 99.0},
            "Bucha Radial O1": {"alarme": 65.0, "trip": 75.0},
            "Bucha Radial O2": {"alarme": 65.0, "trip": 75.0},
            "Gaxeteiro 01": {"alarme": 40.0, "trip": 50.0},
            "Gaxeteiro 02": {"alarme": 38.0, "trip": 48.0},
            "Gaxeteiro 03": {"alarme": 38.0, "trip": 48.0},
            "Óleo U.H.L.M.": {"alarme": 55.0, "trip": 65.0},
            "Óleo U.H.R.V.": {"alarme": 51.0, "trip": 55.0},

        },
        'UG-02': {
            "Enrolamento Fase A": {"alarme": 105.0, "trip": 110.0},
            "Enrolamento Fase B": {"alarme": 105.0, "trip": 110.0},
            "Enrolamento Fase C": {"alarme": 105.0, "trip": 110.0},
            "Mancal L.A. Guia": {"alarme": 65.0, "trip": 72.0},
            "Mancal L.N.A. Guia": {"alarme": 80.0, "trip": 85.0},
            "Mancal L.N.A. Escora": {"alarme": 92.0, "trip": 99.0},
            "Bucha Radial O1": {"alarme": 65.0, "trip": 75.0},
            "Bucha Radial O2": {"alarme": 65.0, "trip": 75.0},
            "Gaxeteiro 01": {"alarme": 40.0, "trip": 50.0},
            "Gaxeteiro 02": {"alarme": 38.0, "trip": 48.0},
            "Gaxeteiro 03": {"alarme": 38.0, "trip": 48.0},
            "Óleo U.H.L.M.": {"alarme": 55.0, "trip": 60.0},
            "Óleo U.H.R.V.": {"alarme": 55.0, "trip": 65.0},
        },
    },
    'CGH HOPPEN': {
        'UG-01': {
            "Enrolamento Fase A": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase B": {"alarme": 100.0, "trip": 110.0},
            "Enrolamento Fase C": {"alarme": 100.0, "trip": 110.0},
            "Nucleo Estator": {"alarme": 100.0, "trip": 110.0},
            "Vedação Eixo L.N.A.": {"alarme": 30.0, "trip": 35.0},
            "Vedação Eixo L.A.": {"alarme": 30.0, "trip": 35.0},
            "Mancal Escora Comb.": {"alarme": 50.0, "trip": 55.0},
            "Mancal Radial Comb.": {"alarme": 50.0, "trip": 55.0},
            "Mancal Radial Guia": {"alarme": 50.0, "trip": 55.0},
            "Contra Escora Mancal Combinado": {"alarme": 50.0, "trip": 55.0},
            "Mancal Rad. Comb. L.A.": {"alarme": 54.0, "trip": 60.0},
            "Mancal Rad. Comb. L.N.A.": {"alarme": 54.0, "trip": 60.0},
            "Óleo U.H.R.V.": {"alarme": 50.0, "trip": 55.0},
            "Óleo U.H.L.M.": {"alarme": 50.0, "trip": 55.0},
            "CS-U1": {"alarme": 70.0, "trip": 75.0},
            "Comb. Casq. Radial": {"alarme": 54.0, "trip": 55.0},

        },
        'UG-02': {
                "Enrolamento Fase A": {"alarme": 100.0, "trip": 110.0},
                "Enrolamento Fase B": {"alarme": 100.0, "trip": 110.0},
                "Enrolamento Fase C": {"alarme": 100.0, "trip": 110.0},
                "Nucleo Estator": {"alarme": 100.0, "trip": 110.0},
                "Vedação Eixo L.N.A.": {"alarme": 31.0, "trip": 35.0},
                "Vedação Eixo L.A.": {"alarme": 31.0, "trip": 35.0},
                "Mancal Escora Comb.": {"alarme": 50.0, "trip": 55.0},
                "Mancal Radial Comb.": {"alarme": 50.0, "trip": 55.0},
                "Mancal Radial Guia": {"alarme": 50.0, "trip": 55.0},
                "Mancal Rad. Comb. L.A.": {"alarme": 52.0, "trip": 60.0},
                "Mancal Rad. Comb. L.N.A.": {"alarme": 52.0, "trip": 57.0},
                "Óleo U.H.R.V.": {"alarme": 50.0, "trip": 55.0},
                "Óleo U.H.L.M.": {"alarme": 52.0, "trip": 55.0},
                "CS-U1": {"alarme": 50.0, "trip": 60.0},
                "Comb. Casq. Radial": {"alarme": 55.0, "trip": 55.0},
                "Cont. Esc. Manc. Comb.": {"alarme": 51.0, "trip": 56.0},

        },
    },
}
